### ISSUE TITLE
Упростить метод.

### ISSUE THREAD

**Issue by prodderman** [Bibigyl/FSD_slider#10]
https://github.com/Bibigyl/FSD_slider/blob/ad050aed085704e9bf6e1a5d7720063ae40fe2fb/src/MVP/Model.ts#L148

Этот метод тяжело воспринимается. Стоит его отрефакторить, сократив количество мутаций и [ответственность по валидации значений](https://github.com/Bibigyl/FSD_slider/issues/9) и возможно разбив на несколько функций.

**Comment by Bibigyl** [comment]
Мне самой не нравился вот этот кусок
![image](https://user-images.githubusercontent.com/44343944/79072279-e2599500-7ce8-11ea-94ce-554ea1734fd3.png)

Исправила
![image](https://user-images.githubusercontent.com/44343944/79072935-5184b880-7cec-11ea-8e0b-11e44a9e0544.png)

В остальном все эти маленькие проверочки очень взаимосвязаны, min и max зависят от customValues, begin и end - почти от всех опций. Я сейчас разобью его на маленькие методы, а старый пока закомментирую, потом выберем что лучше
