### ISSUE TITLE
View

### ISSUE THREAD

**Issue by alextsk** [Bibigyl/FSD_slider#3]
https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L278-L282
в чем разница?

https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L153
зачем as string?

https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L303-L304
имена не отражают назначение

https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L419
булевы переменные именуются c is, has

https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L24
 зачем?

https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L226
@bind  декоратор

https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L258
имя не отражает поведение, валидирует другой метод

во многие методы передается весь объект option, может есть смысл сделать его приватным полем(или группой полей)?

**Comment by Bibigyl** [comment]
>  if ( !reverse ) { 
>      this._thumbFirst.classList.add('slider__thumb_disabled'); 
>  } else { 
>      this._thumbLast.classList.add('slider__thumb_disabled'); 
>  } 
> 
> в чем разница?

thumbFirst - это всегда левый (или верхний) бегунок. thumbLast - всегда правый (нижний).  Если бегунок одиночный, то бегунок который является begin всегда стоит в min и скрыт. Т.е. если реверс, min будет справа и нужно скрыть thumbLast

**Comment by Bibigyl** [comment]
>  const firstThumbPos: number = parseInt( this._thumbFirst.style[topLeft] as string ); 
> 
> зачем as string?

.style.left может вернуть string или null
![image](https://user-images.githubusercontent.com/44343944/76856793-0d290880-6865-11ea-9545-8761b454d9c5.png)

Исправляю на  parseFloat( String(this._thumbFirst.style[topLeft]) );

**Comment by alextsk** [comment]
> Исправляю на parseFloat( String(this._thumbFirst.style[topLeft]) );

если есть дефолт можно сделать this._thumbFirst.style[topLeft] || '100500px'

**Comment by Bibigyl** [comment]
> > Исправляю на parseFloat( String(this._thumbFirst.style[topLeft]) );
> 
> если есть дефолт можно сделать this._thumbFirst.style[topLeft] || '100500px'

нет, тут немного по другому все. Эта переменная только top или left. Это нужно для горизонтального/вертикального вида
![image](https://user-images.githubusercontent.com/44343944/76859206-e7523280-6869-11ea-96f2-aaba12a08a5d.png)

**Comment by Bibigyl** [comment]
>  private validate(options: IViewOptions): void { 
> 
> имя не отражает поведение, валидирует другой метод

Здесь несколько идей, не знаю какая из них верная и что подразумевается под валидацией
1. оставить название validate во вью, а метод validateView изменить на  catchViewWarnings.
2. убрать вообще метод validate. Вынести сохранение ошибок и validateView туда, где раньше вызывался validate и добавить метод handleWarnings / notifyAboutWarnings / transferWarnings / проброситьОшибки (он будет оповещать подписчиков об ошибках если они есть)
3. Изменить название validate на что то вроде handleValidationResults. такое мне не очень нравится, код будет выглядеть непоследовательно

**Comment by Bibigyl** [comment]
> во многие методы передается весь объект option, может есть смысл сделать его приватным полем(или группой полей)?

Если надо сделаю, мне кажется не надо, это данные модели, вью они нужны только чтобы нарисоваться и перерисоваться

**Comment by alextsk** [comment]
> что подразумевается под валидацией

это проверка на корректность, результатом обычно либо ок, либо список того что не соответствует
отправка куда то этих результатов уже отдельная задача

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L19

если вью не хранит стейт, зачем снаружи нужен этот метод?

**Comment by alextsk** [comment]
https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L16-L17
точно клиенту нужно знать разницу между ними? или это можно решить внутри вью?

**Comment by Bibigyl** [comment]
> https://github.com/Bibigyl/FSD_slider/blob/5b65a53871a8b3f6fbb83d43e5faa2e89434c988/src/MVP/View.ts#L19
> 
> если вью не хранит стейт, зачем снаружи нужен этот метод?

Он возвращает опции, связанные со вью - длину, наличие подсказок, наличие шкалы, и вертикальный/горизонтальный вид
