### ISSUE TITLE
При больших значениях числа наслаиваются

### ISSUE THREAD

**Issue by a-poluhin** [Bibigyl/FSD_slider#5]
![image](https://user-images.githubusercontent.com/10168007/78266184-a1ff5780-752f-11ea-8423-db8b638568ec.png)

**Comment by Bibigyl** [comment]
![image](https://user-images.githubusercontent.com/44343944/78278148-48426180-751e-11ea-8477-10fa29f77864.png)
 Надеюсь правильно поняла)
