### ISSUE TITLE
Правка для интервала

### ISSUE THREAD

**Issue by a-poluhin** [Bibigyl/FSD_slider#7]
Еще один момент со шкалой нужно будет поправить: сейчас у тебя можно поставить, например, step: 9 и interval: 10, в итоге получается, что размер шага шкалы не обязательно кратный размеру шага слайдера. Думаю, лучше будет валидировать значение interval у шкалы.
![image](https://user-images.githubusercontent.com/10168007/78267857-a6c50b00-7531-11ea-91b2-39f5d9c4b613.png)

**Comment by Bibigyl** [comment]
Так было перед ревью. Леша сказал переделать на то, что есть сейчас
