### ISSUE TITLE
Валидация options.

### ISSUE THREAD

**Issue by prodderman** [Bibigyl/FSD_slider#9]
https://github.com/Bibigyl/FSD_slider/blob/871609f033696f81e6b6e7120edbae9de87c0543/src/slider.ts#L14

По факту, сюда падает ```IOptions```, а по типам пустой объект, что не правда. 

Также, по-хорошему, нужно сократить ответственность модели и вьюхи,  определив строгий контракт , чтобы они принимали свои и уже валидные options, а логику по валидации вынести на уровень выше.

**Comment by Bibigyl** [comment]
> Также, по-хорошему, нужно сократить ответственность модели и вьюхи, определив строгий контракт , чтобы они принимали свои и уже валидные options, а логику по валидации вынести на уровень выше.

После валидации у меня модель и вью сохраняют свои ошибки(warnings). Потом на основе этих ошибок происходит нормализация. Мне нормализацию тоже вынести на уровень выше? И на уровень выше - это в класс Slider?

**Comment by prodderman** [comment]
> После валидации у меня модель и вью сохраняют свои ошибки(warnings). Потом на основе этих ошибок происходит нормализация. Мне нормализацию тоже вынести на уровень выше? И на уровень выше - это в класс Slider?

Если ты вынесешь валидацию на уровень выше, то в модель и вьюху уже будут попадать корректные значения, которые нормализовать уже будет намного проще, ориентируясь на сами значения.

**Comment by Bibigyl** [comment]
> Если ты вынесешь валидацию на уровень выше, то в модель и вьюху уже будут попадать корректные значения

вот что мне леша писал про валидацию:
что подразумевается под валидацией

это проверка на корректность, результатом обычно либо ок, либо список того что не соответствует
отправка куда то этих результатов уже отдельная задача

То есть валидация ничего не меняет, данные в модель и вью уйдут те же самые

**Comment by Bibigyl** [comment]
Это обсуждение в 3 ишью было

**Comment by prodderman** [comment]
Да, ты права, тебе нужно реализовать механизм отправки, что бы эти "сырые" значения из вне валидировались, разделялись на Вьюшные и Модельные значения, а также проходили предварительную "очистку",  а уже в Вьюхе и Модели нормализовались

**Comment by Bibigyl** [comment]
> проходили предварительную "очистку"

а что именно должно быть в предварительной очистке и что должно остаться в методе нормалайз? И как должна называться функция предварительной очистки - preNormalize, или у подобных функций есть какое то общепринятое название, вроде validate/normalize?

**Comment by prodderman** [comment]
Из вне могу прийти некорректные значения (например min: "2" строкой), или вообще опечатка в свойстве, нужно либо переводить в число либо подставлять значение по-умолчанию. В методе нормалайз должны, как и раньше, нормализоваться значения по типу: если ```begin < min``` то ```begin = min``` и т.д. Такие методы обычно называются ```convert...```

**Comment by Bibigyl** [comment]
> Из вне могу прийти некорректные значения (например min: "2" строкой), или вообще опечатка в свойстве, нужно либо переводить в число либо подставлять значение по-умолчанию. В методе нормалайз должны, как и раньше, нормализоваться значения по типу: если `begin < min` то `begin = min` и т.д. Такие методы обычно называются `convert...`

Это сделать технически несложно, но радикально повлияет на архитектуру, с неприятными последствиями. Мы можем обсудить это в телеграме?
Сейчас проверки о которых ты говорил работают.
